import { BUILDING_TYPE } from '../city/building/constants';

interface AssetId {
  GRASS: 'GRASS';
  GROUND: 'GROUND';
  RESIDENTIAL: typeof BUILDING_TYPE.RESIDENTIAL;
  COMMERCIAL: typeof BUILDING_TYPE.COMMERCIAL;
  INDUSTRIAL: typeof BUILDING_TYPE.INDUSTRIAL;
  ROAD: typeof BUILDING_TYPE.ROAD;
}

const ASSET_ID: AssetId = {
  GRASS: 'GRASS',
  GROUND: 'GROUND',
  RESIDENTIAL: BUILDING_TYPE.RESIDENTIAL,
  COMMERCIAL: BUILDING_TYPE.COMMERCIAL,
  INDUSTRIAL: BUILDING_TYPE.INDUSTRIAL,
  ROAD: BUILDING_TYPE.ROAD,
};

interface AssetCreators {
  [key: string]: (...args: any[]) => THREE.Mesh;
}

export { ASSET_ID, AssetCreators };

